In [18]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [29]:
iris= datasets.load_iris()
X=iris.data
y=iris.target


In [30]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [31]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [32]:
iris.data[1]


array([4.9, 3. , 1.4, 0.2])

In [33]:
iris.data[2]

array([4.7, 3.2, 1.3, 0.2])

In [28]:
 X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

In [40]:
model=LogisticRegression(max_iter=1000 ,random_state=42)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [47]:
y_pred=model.predict(X_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [44]:

sample_data = np.array([[5.1, 3.5, 1.4, 0.2],  # Sample 1
                        [6.5, 3.0, 5.5, 2.0],  # Sample 2
                        [4.9, 2.5, 4.5, 1.7]]) # Sample 3

# Predict the classes of the sample data
predicted_classes = model.predict(sample_data)
predicted_species = iris.target_names[predicted_classes]

for i in range(len(sample_data)):
    print(f"Sample {i+1} - Predicted Class: {predicted_species[i]}")


Sample 1 - Predicted Class: setosa
Sample 2 - Predicted Class: virginica
Sample 3 - Predicted Class: versicolor


In [45]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0
